name: Hello World Workflow

on:
<<<<<<< HEAD
  pull_request:
    branches:
      - master
=======
  workflow_dispatch:
>>>>>>> cf242b0c5814c23b6ca622f1ab87a9c91b2925ca

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"

      - name: Show current date and time
        run: date

      - name: Show current directory
        run: pwd

      - name: List files in current directory
        run: ls -la